/**
 * Tool System
 * ===========
 * Handles material removal when the user clicks on the specimen.
 *
 * Each tool has a radius (brush size) and power (removal strength).
 * Material is removed based on the tool power vs. material hardness.
 *
 * Key concepts:
 *   - Harder materials require more power to remove
 *   - The fire layer is extremely fragile — even fine tools can destroy it
 *   - Tools leave surface roughness proportional to their aggressiveness
 *   - Removal is spherical around the click point
 */

import type { Voxel, ToolName, SimulationWarning } from '../types';
import { TOOLS, MATERIAL_HARDNESS, GRID_SIZE } from '../constants';
import { voxelIndex, inBounds } from './specimenGenerator';

/**
 * Result of a single tool application.
 */
export interface ToolResult {
  /** Updated grid (mutated in place, but also returned for convenience). */
  grid: Voxel[];
  /** Number of voxels removed in this stroke. */
  removed: number;
  /** Number of fire voxels destroyed in this stroke. */
  fireDestroyed: number;
  /** Any warnings generated by this stroke. */
  warnings: SimulationWarning[];
}

/**
 * Apply a tool stroke at the given grid coordinates.
 *
 * @param grid     - The full voxel grid (mutated in place)
 * @param toolName - Which burr tool is selected
 * @param cx, cy, cz - Centre of the stroke in grid coordinates
 * @returns ToolResult with counts and warnings
 */
export function applyTool(
  grid: Voxel[],
  toolName: ToolName,
  cx: number,
  cy: number,
  cz: number
): ToolResult {
  const tool = TOOLS[toolName];
  const warnings: SimulationWarning[] = [];
  let removed = 0;
  let fireDestroyed = 0;

  const r = tool.radius;

  // Iterate over all voxels within the brush sphere
  for (let dx = -r; dx <= r; dx++) {
    for (let dy = -r; dy <= r; dy++) {
      for (let dz = -r; dz <= r; dz++) {
        // Only affect voxels within the sphere (not a cube)
        const dist = Math.sqrt(dx * dx + dy * dy + dz * dz);
        if (dist > r) continue;

        const x = Math.round(cx) + dx;
        const y = Math.round(cy) + dy;
        const z = Math.round(cz) + dz;

        if (!inBounds(x, y, z)) continue;

        const idx = voxelIndex(x, y, z);
        const voxel = grid[idx];

        // Skip air — nothing to remove
        if (voxel.material === 'air') continue;

        // Calculate removal effectiveness
        // Tool power falls off with distance from stroke centre
        const falloff = 1 - dist / (r + 0.5);
        const effectivePower = tool.power * falloff;
        const hardness = MATERIAL_HARDNESS[voxel.material] ?? 0.5;

        // Removal chance: power must overcome hardness
        // For matrix (hardness 0.3), even a fine tool (power 0.1) can remove
        // For fire (hardness 0.15), ANY tool can destroy it — this is the danger
        if (effectivePower > hardness * 0.3) {
          // Reduce integrity
          const damage = effectivePower / Math.max(hardness, 0.1);
          voxel.integrity -= damage;

          if (voxel.integrity <= 0) {
            // Voxel is fully removed
            if (voxel.material === 'fire') {
              fireDestroyed++;
            }
            voxel.material = 'air';
            voxel.integrity = 0;
            voxel.roughness = 0;
            voxel.depth = 0;
            removed++;
          } else {
            // Partially damaged: increase roughness from tool
            voxel.roughness = Math.min(
              1,
              voxel.roughness + tool.roughnessEffect * 0.3
            );
          }
        }
      }
    }
  }

  // Generate warnings based on what happened
  const now = Date.now();

  if (fireDestroyed > 0) {
    warnings.push({
      id: `fire-destroyed-${now}`,
      message: `⚠ Destroyed ${fireDestroyed} fire voxel${fireDestroyed > 1 ? 's' : ''}! Use a finer tool near fire layers.`,
      severity: 'danger',
      timestamp: now,
    });
  }

  if (removed > 10 && toolName === 'coarse') {
    warnings.push({
      id: `aggressive-${now}`,
      message: 'Large chunk removed. Check for undercut risk.',
      severity: 'warning',
      timestamp: now,
    });
  }

  return { grid, removed, fireDestroyed, warnings };
}
